networks:
  trinity_network:

services:
  trinity:
    container_name: trinity
    image: nathancahgn/t-dev-700-ren_3:latest
    ports:
      - "8080:3000"
    networks:
      - trinity_network
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma db push &&
      npx prisma generate &&
      npx prisma db seed &&
      npm run dev
      "
  db:
    container_name: db_trinity
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - trinity_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    container_name: ProxyManager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - trinity_network
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
volumes:
  postgres_data: